print()
print()

line1 = ("*"*23).center(44, " ")
line2 = ("*                     *").center(44, " ")
line3 = ("*  MAK's Dining Room  *").center(44, " ")
print(line1)
print(line2)
print(line3)
print(line2)
print(line1)

print()
print(" Restaurant menu ".upper().center(40, "*"))
print()
print("Breakfast".center(40, " "))
print("Poached Egg".ljust(34, "."), "$2.00".rjust(6, " "))
print("Toasted English Muffin".ljust(34, "."), "$3.00".rjust(6, " "))
print("Waffles".ljust(34, "."), "$2.99".rjust(6, " "))
print("Bagles".ljust(34, "."), "$1.99".rjust(6, " "))
print()
print("Meals".center(40, " "))
print("MAk n cheese".title().ljust(34, "."), "$3.00".rjust(6, " "))
print("Fajeeta".title().ljust(34, "."), "$3.00".rjust(6, " "))
print("Beef stroganoff".title().ljust(34, "."), "$4.00".rjust(6, " "))
print("Staek and Potatoes".title().ljust(34, "."), "$1.99".rjust(6, " "))
print()
print("Drinks".center(40, " "))
print("Black coffee".title().ljust(34, "."), "$1.00".rjust(6, " "))
print("Regular coffee".title().ljust(34, "."), "$1.00".rjust(6, " "))
print("Iced coffee".title().ljust(34, "."), "$1.00".rjust(6, " "))
print("green tea".title().ljust(34, "."), "$1.00".rjust(6, " "))